spin_manifest_version = 2

[application]
name = "bookmark-ai-links"
version = "0.1.0"
authors = ["admin <thando.mafela@gmail.com>"]
description = "Application to book mark my ai queries"

[[trigger.http]]
route = "/..."
component = "web"

[component.web]
source = "web/target/wasm32-wasip1/release/web.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.web.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "web"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/static/..."
component = "assets"

[component.assets]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
